### ISSUE TITLE
Add BigQuery lineage using Dataplex Lineage API

### ISSUE THREAD

**Issue by criccomini** [recap-cloud/recap#176]
Seems like the BigQuery lineage API hasn't been implemented server-side yet:

```
from google.cloud.datacatalog.lineage import LineageClient, SearchLinksRequest, EntityReference
client = LineageClient()
er = EntityReference(fully_qualified_name='bigquery:some-project-1234.austin_311.311_service_requests')
sr = SearchLinksRequest(parent='some-project-1234', source=er)
client.search_links(request=sr)
```

Gives me:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chrisriccomini/Code/recap/.venv/lib/python3.10/site-packages/google/cloud/datacatalog/lineage_v1/services/lineage/client.py", line 2168, in search_links
    response = rpc(
  File "/Users/chrisriccomini/Code/recap/.venv/lib/python3.10/site-packages/google/api_core/gapic_v1/method.py", line 113, in __call__
    return wrapped_func(*args, **kwargs)
  File "/Users/chrisriccomini/Code/recap/.venv/lib/python3.10/site-packages/google/api_core/grpc_helpers.py", line 74, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.MethodNotImplemented: 501 Received http2 header with status: 404
```

Doesn't seem like the API has been implemented server side? Odd...

I'm not 100% sure the objects I made are correctly set up. I'm following:

https://cloud.google.com/python/docs/reference/lineage/latest/google.cloud.datacatalog.lineage_v1.services.lineage.LineageClient
https://cloud.google.com/python/docs/reference/lineage/latest/google.cloud.datacatalog.lineage_v1.types.EntityReference
https://cloud.google.com/python/docs/reference/lineage/latest/google.cloud.datacatalog.lineage_v1.types.SearchLinksRequest

**Comment by criccomini** [comment]
Might be worth looking at open lineage for this
